version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fullstack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fullstackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    networks:
      - fullstack-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: fullstack-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/fullstackdb
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - fullstack-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: fullstack-frontend
    restart: unless-stopped
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks:
      - fullstack-network

volumes:
  postgres_data:

networks:
  fullstack-network:
    driver: bridge